name: Deploy Testkube
description: Install and configure Testkube

runs:
  using: "composite"

  steps:

    - name: Installing Testkube Helm repository
      shell: bash
      run: |
        helm repo add kubeshop https://kubeshop.github.io/helm-charts

    - name: Deploy Testkube using Helm
      if: env.TK_SUBSCRIPTION == 'free'
      shell: bash
      run: |-
        helm upgrade --install --atomic --timeout 600s testkube kubeshop/testkube --namespace testkube --create-namespace

        kubectl describe pods -n testkube -l app.kubernetes.io/name=api-server

    - name: Setup Testkube CLI
      if: env.TK_SUBSCRIPTION == 'free'
      uses: kubeshop/setup-testkube@v1
      with:
        namespace: testkube

    - name: Deploy Testkube using Helm
      if: env.TK_SUBSCRIPTION == 'pro'
      shell: bash
      run: |-
        helm upgrade --install --reuse-values --create-namespace testkube kubeshop/testkube \
          --set testkube-api.cloud.key=$TK_AGENT \
          --set testkube-api.cloud.orgId=$TK_ORGANIZATION \
          --set testkube-api.cloud.envId=$TK_ENVIRONMENT \
          --set testkube-api.minio.enabled=false --set mongodb.enabled=false \
          --set testkube-dashboard.enabled=false --set testkube-api.cloud.url=agent.testkube.io:443 \
          --namespace testkube

        kubectl describe pods -n testkube -l app.kubernetes.io/name=api-server

    - name: Setup Testkube Pro
      if: env.TK_SUBSCRIPTION == 'pro'
      uses: kubeshop/setup-testkube@v1
      with:
        namespace: testkube
        organization: ${{ env.TK_ORGANIZATION }}
        environment: ${{ env.TK_ENVIRONMENT }}
        token: ${{ env.TK_TOKEN }}
