name: Deploy Testkube
description: Install and configure Testkube

runs:
  using: "composite"

  steps:

    - name: Installing Testkube Helm repository
      shell: bash
      run: |
        helm repo add kubeshop https://kubeshop.github.io/helm-charts

    - name: Deploy Testkube using Helm
      shell: bash
      run: |-
        helm upgrade --install --atomic --timeout 600s testkube kubeshop/testkube --namespace testkube --create-namespace

    - name: Setup Testkube CLI
      uses: kubeshop/setup-testkube@v1
      with:
        namespace: testkube
