name: Upload results
description: Upload results from tests as artifact

runs:
  using: "composite"

  steps:

    - name: Store test results
      shell: bash
      run: |
        mkdir -p ${{ github.workspace }}/test-results
        
        for test in $(kubectl get tests.tests.testkube.io -n testkube --no-headers -o custom-columns=":metadata.name") ; do
          testkube get execution $test-$RUN_ID-$JOB_ID --output json > ${{ github.workspace }}/test-results/$test-$RUN_ID-$JOB_ID.json
        done
        
        for test in $(kubectl get testsuite.tests.testkube.io -n testkube --no-headers -o custom-columns=":metadata.name") ; do
          testkube get execution $test-$RUN_ID-$JOB_ID --output json > ${{ github.workspace }}/test-results/$test-$RUN_ID-$JOB_ID.json
        done
        
        kubectl get testworkflows.testworkflows.testkube.io -n testkube
        
        kubectl get testworkflows.testworkflows.testkube.io -n testkube -o yaml
        
        kubectl get testworkflowexecutions.testworkflows.testkube.io -n testkube
        
        kubectl get testworkflowexecutions.testworkflows.testkube.io -n testkube --no-headers -o custom-columns=":metadata.name"
        
        kubectl get testworkflowexecutions.testworkflows.testkube.io -n testkube -o yaml
        
        testkube get testworkflow
        testkube get testworkflowexecution
        
        for testworkflow in $(kubectl get testworkflows.testworkflows.testkube.io -n testkube --no-headers -o custom-columns=":metadata.name") ; do
          testkube get testworkflowexecution $testworkflow-$RUN_ID-$JOB_ID --output json > ${{ github.workspace }}/test-results/$testworkflow-$RUN_ID-$JOB_ID.json
        done

    - name: Upload test results as artifact
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: ${{ github.workspace }}/test-results
