name: Upload results
description: Upload results from tests as artifact

runs:
  using: "composite"

  steps:

    - name: Store test results
      shell: bash
      run: |
        mkdir -p ${{ github.workspace }}/test-results
        
        echo "Tests:"
        testkube get test
        echo "Test executions:"
        testkube get execution
        for test in $(kubectl get tests.tests.testkube.io -n testkube --no-headers -o custom-columns=":metadata.name") ; do
          testkube get execution $test-$RUN_ID-$JOB_ID --output json > ${{ github.workspace }}/test-results/$test-$RUN_ID-$JOB_ID.json
        done
        
        echo "Test suites:"
        testkube get testsuite
        echo "Test suite executions:"
        testkube get testsuiteexecution
        for test in $(kubectl get testsuite.tests.testkube.io -n testkube --no-headers -o custom-columns=":metadata.name") ; do
          testkube get execution $test-$RUN_ID-$JOB_ID --output json > ${{ github.workspace }}/test-results/$test-$RUN_ID-$JOB_ID.json
        done
        
        echo "Test workflows:"
        testkube get testworkflow
        echo "Test workflow executions:"
        testkube get testworkflowexecution
        for id in $(testkube get testworkflowexecution --output json | jq -r '.[].id'); do
          testkube get testworkflowexecution $id --output pretty > ${{ github.workspace }}/test-results/$id-$RUN_ID-$JOB_ID.pretty
          testkube get testworkflowexecution $id --output json > ${{ github.workspace }}/test-results/$id-$RUN_ID-$JOB_ID.json
        done

    - name: Upload test results as artifact
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: ${{ github.workspace }}/test-results

#    - name: Upload test artifacts
#      uses: actions/upload-artifact@v4
#      with:
#        name: test-artifacts
#        path: ${{ github.workspace }}/artifacts
