name: Create k8s cluster
description: Install and configure a k8s cluster based on selected distribution

inputs:
  dist:
    description: 'Distribution name of k8s cluster'
    required: true
    default: 'rke2'

runs:
  using: "composite"

  steps:
    - run: |
        ls -la
        ls -la .github
        ls -la .github/actions
      shell: bash

    - name: Create microk8s cluster
      if: ${{ inputs.dist }} == 'microk8s'
      uses: ./.github/actions/create-microk8s-cluster
