name: Initialize data
description: Initialize data for test results or database

runs:
  using: "composite"

  steps:

    # Initialize database with the data from the initdb folder
    - name: Initialize database
      shell: bash
      env:
        PGPASSWORD: ${{ env.POSTGRES_PASSWORD }}
      run: |
        for entry in "$TEST_FOLDER_PATH/initdb"/*
        do
          psql -h localhost -U $POSTGRES_USER -d $POSTGRES_DB -f $entry
        done
