name: Run tests
description: Apply Testkube CRDs and run all testworkflows

runs:
  using: "composite"

  steps:

    - name: Create Testkube CRDs
      shell: bash
      run: |
        kubectl apply -f $TEST_FOLDER_PATH/tests/testworkflow --recursive

    - name: Run all testworkflows
      shell: bash
      run: |
        LABEL="ci-run=${RUN_ID}-${JOB_ID}"
        for testworkflow in $(kubectl get testworkflows.testworkflows.testkube.io -n testkube --no-headers -o custom-columns=":metadata.name") ; do
          testkube run testworkflow $testworkflow --name $testworkflow-$RUN_ID-$JOB_ID --label $LABEL
        done

    - name: Wait for testworkflows to finish
      shell: bash
      run: |
        kubectl -n testkube get jobs.batch -o wide
        
        kubectl -n testkube wait job --for=condition=complete --timeout=600s & pidOK=$!
        kubectl -n testkube wait job --for=condition=failed --timeout=600s & pidFail=$!
        
        wait -n "$pidOK" "$pidFail"
