name: Send notification through Teams
description: Send notification about failed tests through Teams

inputs:
  dist:
    description: 'Notification type'
    required: true
    default: 'teams'

runs:
  using: "composite"

  steps:

    - name: Notify about failed tests in Teams
      shell: bash
      run: |
        for test in $(kubectl get tests.tests.testkube.io -n testkube --no-headers -o custom-columns=":metadata.name") ; do
          if [[ $(jq -r '.executionResult.status' ${{ github.workspace }}/test-results/$test-$RUN_ID-$JOB_ID.json) != "passed" ]]; then
            export EXECUTION_ID=$(jq -r '.id' ${{ github.workspace }}/test-results/$test-$RUN_ID-$JOB_ID.json)
            export TEST_LABELS=$(jq '.labels' ${{ github.workspace }}/test-results/$test-$RUN_ID-$JOB_ID.json | sed 's/$/\\n/g' | tr -d '\n' | sed 's/"/\\"/g')
            export TEST_TYPE=$(jq -r '.testType' ${{ github.workspace }}/test-results/$test-$RUN_ID-$JOB_ID.json)
            export TEST_NAME="$test"
        
            envsubst < ${{ github.workspace }}/adaptive_card_template.json > ${{ github.workspace }}/adaptive_card.json
            curl -X POST --silent \
              -H "Content-Type: application/json" -d @${{ github.workspace }}/adaptive_card.json \
              $TEAMS_INCOMING_WEBHOOK_URL
          fi
        done
        
        for test in $(kubectl get testsuite.tests.testkube.io -n testkube --no-headers -o custom-columns=":metadata.name") ; do
          if [[ $(jq -r '.status' ${{ github.workspace }}/test-results/$test-$RUN_ID-$JOB_ID.json) != "passed" ]]; then
            export EXECUTION_ID=$(jq -r '.id' ${{ github.workspace }}/test-results/$test-$RUN_ID-$JOB_ID.json)
            export TEST_LABELS="test-suite"
            export TEST_TYPE="test-suite"
            export TEST_NAME="$test"
        
            envsubst < ${{ github.workspace }}/adaptive_card_template.json > ${{ github.workspace }}/adaptive_card.json
            curl -X POST --silent \
              -H "Content-Type: application/json" -d @${{ github.workspace }}/adaptive_card.json \
              $TEAMS_INCOMING_WEBHOOK_URL
          fi
        done
