#!/usr/bin/env bash
# Phase: provision the timestamping objects through scripts/timestamping-setup.sh and
# hand the suite a machine-readable summary of what exists.
#
# The setup script reuses every named object it finds but always issues a fresh certificate
# for a set it has to create, so the certificate DN and the key name must be unique per
# *fresh* provisioning: EJBCA rejects a second end entity bound to an already-used key.
# Both names are therefore pinned in .state/provisioning.env for as long as the database
# survives, and regenerated whenever that state is gone (first run, or after --clean).

provisioning_state_file() { echo "${SUITE_DIR}/.state/provisioning.env"; }

load_or_create_provisioning_names() {
  local state_file
  state_file=$(provisioning_state_file)
  mkdir -p "$(dirname "$state_file")"

  if [[ -f "$state_file" ]]; then
    # shellcheck disable=SC1090
    source "$state_file"
    log "reusing provisioning identity from $(basename "$state_file"): ${CERTIFICATE_DN}"
    return 0
  fi

  rotate_provisioning_names
  log "new provisioning identity: ${CERTIFICATE_DN}"
}

# A failed attempt may already have issued a certificate and bound the key to an EJBCA end
# entity, and EJBCA refuses a second end entity on the same key. Every attempt after a
# failure therefore starts from fresh names.
rotate_provisioning_names() {
  local stamp; stamp=$(date +%Y%m%d-%H%M%S)
  CERTIFICATE_DN="regression-${stamp}"
  KEY_NAME="tsa-rsa-${stamp}"
}

write_provisioning_state() {
  cat > "$(provisioning_state_file)" <<EOF
# Generated by the timestamping regression runner. Delete to force fresh certificates.
CERTIFICATE_DN="${CERTIFICATE_DN}"
KEY_NAME="${KEY_NAME}"
EOF
}

discard_provisioning_state() {
  rm -f "$(provisioning_state_file)"
}

# The ssl-client-cert header only authenticates once the certificate is registered as an
# administrator, which a wiped database no longer has.
bootstrap_admin_if_needed() {
  if ilm_api GET /v1/connectors >/dev/null 2>&1; then return 0; fi

  log "admin certificate not recognised — registering it through the Local API"
  local cert_b64 payload response
  cert_b64=$(sed -n '/-----BEGIN CERTIFICATE-----/,/-----END CERTIFICATE-----/p' "$ADMIN_CERT_PEM" \
    | grep -v "^-----" | tr -d '\n\r')
  payload=$(jq -n --arg cert "$cert_b64" \
    '{certificateData: $cert, certificateUuid: "", username: "adminadmin", firstname: "admin",
      lastname: "admin", email: "admin@ilm.local", enabled: "true", description: "First Administrator"}')
  response=$(curl -s -X POST -H 'content-type: application/json' -d "$payload" \
    "${ILM_HOST}/api/v1/local/admins" 2>&1) || true

  ilm_api GET /v1/connectors >/dev/null 2>&1 \
    || die "Admin certificate still not accepted after bootstrapping. Local API said: ${response}"
  ok "administrator registered"
}

run_setup_script() {
  local log_file="$1"
  # The connectors are registered by their host-published ports in both modes; only the host
  # differs, because a containerised Core reaches those ports through the host gateway.
  "${DEV_DIR}/scripts/timestamping-setup.sh" \
    --ilm-host "$ILM_HOST" \
    --connector-host "$CONNECTOR_HOST" \
    --client-cert-pem "$ADMIN_CERT_PEM" \
    --pkcs12-bundle "$EJBCA_PKCS12_BUNDLE" \
    --pkcs12-password "$EJBCA_PKCS12_PASSWORD" \
    --certificate-dn "$CERTIFICATE_DN" \
    --key-name "$KEY_NAME" \
    --json-summary "${RUN_DIR}/provisioning.json" \
    > "$log_file" 2>&1
}

# --- Repair: issuing CA missing from the platform -----------------------------
# Symptom: "issuerCertificateUuid is still empty after N attempts", later surfacing as
# "Certificate is not eligible for signing workflow type TIMESTAMPING". The leaf cannot be
# validated because its issuer was never uploaded, so the signing profile is refused.
# Fix: pull the CA from the leaf's AIA extension, upload it, trust it, revalidate the leaf.
needs_issuer_ca_repair() {
  grep -q -e "issuerCertificateUuid is still empty" \
          -e "not eligible for signing workflow type TIMESTAMPING" "$1"
}

newest_certificate_uuid_by_common_name() {
  local common_name="$1" response
  response=$(ilm_api POST /v1/certificates -d '{"itemsPerPage":100,"pageNumber":1,"filters":[]}') || return 1
  echo "$response" | jq -r --arg cn "$common_name" \
    '[.certificates[]? | select(.commonName == $cn)] | sort_by(.notBefore) | last | .uuid // empty'
}

upload_and_trust_issuer_ca() {
  local leaf_uuid="$1" work_dir="${RUN_DIR}/repair"
  mkdir -p "$work_dir"

  local leaf_json content aia_uri ca_b64 upload_response root_uuid
  leaf_json=$(ilm_api GET "/v1/certificates/${leaf_uuid}") || return 1
  content=$(echo "$leaf_json" | jq -r '.certificateContent // empty')
  [[ -n "$content" ]] || { warn "repair: leaf ${leaf_uuid} has no certificate content"; return 1; }

  printf -- "-----BEGIN CERTIFICATE-----\n%s\n-----END CERTIFICATE-----\n" "$content" > "${work_dir}/leaf.pem"
  aia_uri=$(openssl x509 -in "${work_dir}/leaf.pem" -noout -ext authorityInfoAccess 2>/dev/null \
    | sed -n 's/.*CA Issuers - URI:\(.*\)/\1/p' | head -1 | tr -d '[:space:]')
  [[ -n "$aia_uri" ]] || { warn "repair: leaf has no CA Issuers URI in its AIA extension"; return 1; }

  log "repair: fetching the issuing CA from ${aia_uri}"
  curl -s -f -o "${work_dir}/issuer.der" "$aia_uri" || { warn "repair: could not download ${aia_uri}"; return 1; }
  ca_b64=$(base64 < "${work_dir}/issuer.der" | tr -d '\n')

  upload_response=$(ilm_api POST /v1/certificates/upload \
    -d "$(jq -n --arg cert "$ca_b64" '{certificate: $cert, customAttributes: []}')") \
    || { warn "repair: CA upload failed: ${upload_response}"; return 1; }
  root_uuid=$(echo "$upload_response" | jq -r '.uuid // empty')
  [[ -n "$root_uuid" ]] || { warn "repair: upload returned no UUID: ${upload_response}"; return 1; }

  ilm_api PATCH "/v1/certificates/${root_uuid}" -d '{"trustedCa": true}' >/dev/null \
    || { warn "repair: could not mark ${root_uuid} as trusted"; return 1; }
  # Trusting the root does not revalidate anything by itself; ask for the leaf's validation.
  ilm_api GET "/v1/certificates/${leaf_uuid}/validate" >/dev/null || true
  ok "repair: issuing CA ${root_uuid} uploaded and trusted"
}

attempt_issuer_ca_repair() {
  local leaf_uuid suffix
  for suffix in non-qualified qualified; do
    leaf_uuid=$(newest_certificate_uuid_by_common_name "${CERTIFICATE_DN}-${suffix}") || continue
    [[ -n "$leaf_uuid" ]] || continue
    upload_and_trust_issuer_ca "$leaf_uuid" && return 0
  done
  return 1
}

phase_provision() {
  section "Provisioning"
  load_or_create_provisioning_names
  bootstrap_admin_if_needed

  # The identity is only recorded once a run has actually succeeded with it; a failed
  # attempt must never be reused, because its key may already be bound in EJBCA.
  local log_file="${RUN_DIR}/provisioning.log"
  if run_setup_script "$log_file"; then
    write_provisioning_state
    ok "provisioning complete — summary: ${RUN_DIR}/provisioning.json"
    return 0
  fi

  discard_provisioning_state

  if ! needs_issuer_ca_repair "$log_file"; then
    tail -25 "$log_file" >&2
    die "Provisioning failed — full log: ${log_file}"
  fi

  warn "provisioning failed because the issuing CA is not in the platform; repairing and retrying once"
  attempt_issuer_ca_repair || { tail -25 "$log_file" >&2; die "Repair failed — full log: ${log_file}"; }

  rotate_provisioning_names
  log "retrying with ${CERTIFICATE_DN}"

  log_file="${RUN_DIR}/provisioning-retry.log"
  run_setup_script "$log_file" || { tail -25 "$log_file" >&2; die "Provisioning failed after repair — full log: ${log_file}"; }
  write_provisioning_state
  ok "provisioning complete after repair — summary: ${RUN_DIR}/provisioning.json"
}
