#!/usr/bin/env bash
# Published components: images taken from the registry instead of built from a checkout.
#
# The resolved reference reaches Compose through a generated overlay rather than by retagging
# the image locally. The overlay is a readable record of what a run actually used, it leaves
# the registry's own tags meaning what they mean, and it needs no edit to ilm-compose.yml —
# the development-environment repository stays free to evolve.

# Compose additions a published component needs beyond a pinned image. Only Core has any:
# its Compose service predates this suite and is wired for a developer poking at the API by
# hand, not for the regression run.
overlay_service_extras() {
  [[ "$1" == "core" ]] || return 0
  cat <<YAML
    environment:
      # Without it Core never subscribes to the time-quality exchange, and every qualified
      # timestamp fails with "time quality is not sufficient" and no other clue.
      - MESSAGING_TIME_QUALITY_ENABLED=true
      # The Compose service hardcodes DEBUG; honour the same setting as a host Core.
      - LOGGING_LEVEL_COM_OTILM=${CORE_LOG_LEVEL:-INFO}
    extra_hosts:
      # Provisioning registers the connectors on their host-published ports, which a
      # containerised Core can only reach back through the host gateway.
      - "host.docker.internal:host-gateway"
YAML
}

# Rewritten on every invocation, including --status and --teardown, so the file on disk
# always describes the current selection rather than whatever the last full run left.
write_published_overlay() {
  local file component service ref extras services=""
  file=$(published_overlay_file)
  mkdir -p "$(dirname "$file")"

  for component in "${ALL_COMPONENTS[@]}"; do
    component_is_local "$component" && continue
    service=$(component_service "$component") || continue
    ref=$(component_image_ref "$component") || continue
    services+="$(printf '  %s:\n    image: %s\n' "$service" "$ref")"$'\n'
    extras=$(overlay_service_extras "$component")
    [[ -n "$extras" ]] && services+="${extras}"$'\n'
  done

  # `services:` with no children is not valid Compose, so an empty overlay must not exist.
  if [[ -z "$services" ]]; then
    rm -f "$file"
    return 0
  fi

  { echo "# Generated by the timestamping regression runner — edits are overwritten."
    echo "# Pins every component this run takes from the registry."
    echo "services:"
    printf '%s' "$services"
  } > "$file"
}

# A private repository needs a session that expired quietly hours ago; say so once, naming
# the registry, instead of letting every pull fail with Docker's own wording.
registry_login_hint() {
  echo "If the pull was denied, the registry session has expired: docker login ${1%%/*}"
}

pull_published_images() {
  local component ref digest log_file="${RUN_DIR}/pull-images.log" published=()

  for component in "${ALL_COMPONENTS[@]}"; do
    component_is_local "$component" && continue
    component_service "$component" >/dev/null || continue
    component_image_base "$component" >/dev/null || continue
    published+=("$component")
  done
  [[ ${#published[@]} -eq 0 ]] && return 0

  log "docker pull: ${published[*]}"
  for component in "${published[@]}"; do
    ref=$(component_image_ref "$component")
    docker pull --quiet "$ref" >> "$log_file" 2>&1 \
      || die "${component}: docker pull ${ref} failed — see ${log_file}
    $(registry_login_hint "$ref")"

    # The digest is the only stable identity of a moving tag like develop-latest, and the
    # only thing that makes a QA result reproducible later.
    digest=$(docker image inspect -f '{{if .RepoDigests}}{{index .RepoDigests 0}}{{end}}' "$ref" 2>/dev/null)
    digest="${digest##*@}"
    manifest_component "$component" "$(jq -n --arg image "$ref" --arg tag "$(component_tag "$component")" \
      --arg digest "$digest" '{source: "published", image: $image, tag: $tag, digest: $digest}')"
    ok "$(printf '%-32s %s' "$component" "${digest:-unknown}" | cut -c1-70)"
  done
}
